version: '3'

services:
  node-app:
    build: .
    image: node-app
    env_file:
      - .env
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - node-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb-back-up:/data/db
    networks:
      - node-network
    command: ["--replSet", "rs0"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  node-network:
    driver: bridge
