version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb-back-up:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
